# Generated by Django 4.2.1 on 2023-06-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0003_alter_custommember_mbr_pw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="custommember",
            name="mbr_pw",
            field=models.CharField(max_length=100),
        ),
    ]
