# Generated by Django 4.2.1 on 2023-06-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0010_remove_board_mbr_no_board_member"),
        ("member", "0005_alter_custommember_mbr_mail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="customMember",
        ),
    ]
