# Generated by Django 4.2.1 on 2023-06-08 20:26

from django.db import migrations, models
import django.db.models.deletion
import mosaicImg.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("board", "0010_remove_board_mbr_no_board_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="MosaicImg",
            fields=[
                ("mos_no", models.AutoField(primary_key=True, serialize=False)),
                ("mos_up", models.FileField(upload_to=mosaicImg.models.upload_path)),
                ("mos_down", models.CharField(max_length=255, null=True)),
                (
                    "board_no",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="board.board",
                    ),
                ),
            ],
            options={
                "db_table": "MosaicImg",
            },
        ),
    ]
