# Generated by Django 4.2.1 on 2023-05-25 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                ("board_no", models.AutoField(primary_key=True, serialize=False)),
                ("board_title", models.CharField(max_length=100)),
                ("board_content", models.TextField(null=True)),
                ("board_upload", models.FileField(upload_to="")),
                ("board_download", models.FileField(upload_to="")),
                ("board_date", models.DateTimeField(auto_now_add=True)),
                (
                    "mbr_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Board",
            },
        ),
    ]
