# Generated by Django 4.2.1 on 2023-05-26 11:44

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0002_alter_board_board_download"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='board_download',
        ),
        migrations.RemoveField(
            model_name='board',
            name='board_upload',
        ),
    ]
