# Generated by Django 4.2.1 on 2023-05-26 11:48

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_alter_board_board_download_alter_board_board_upload"),
    ]
