# Generated by Django 4.2.1 on 2023-05-26 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_alter_board_board_download"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="board_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
