# Generated by Django 4.2.1 on 2023-05-31 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_alter_board_board_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="mbr_no",
        ),
    ]
