# Generated by Django 4.2.1 on 2023-05-31 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0002_alter_custommember_groups_and_more"),
        ("board", "0008_remove_board_mbr_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="mbr_no",
            field=models.ForeignKey(
                default=1113,
                on_delete=django.db.models.deletion.CASCADE,
                to="member.custommember",
            ),
            preserve_default=False,
        ),
    ]
