# Generated by Django 4.2.1 on 2023-06-08 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("board", "0009_board_mbr_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="mbr_no",
        ),
        migrations.AddField(
            model_name="board",
            name="member",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
